### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by ryanshrott** [trevorhobenshield/amazon_photos#1]
How can I upload to specific folders, and create them if they don't exist?

**Comment by trevorhobenshield** [comment]
Great question, If you want to upload to a specific directory you just need to copy the heirarchy:

Given an example Amazon Photos filesystem:
```
~ 
├── Documents 
├── Pictures 
│   ├── iPhone 
│   └── Web 
└── Videos 
```

On the website the default upload path is `~/Pictures/Web`

If you also want to upload to `~/Pictures/Web` you would create that directory structure locally, add your images in there, and then run:

```python
ap.upload('Pictures/Web')
```

If you upload to directories that don't exist, it creates them, so:

```python
ap.upload('hello/world')
```

results in:

```
~ 
├── hello 
│   └── world 
├── Documents 
├── Pictures 
│   ├── iPhone 
│   └── Web 
└── Videos 
```
