### ISSUE TITLE
The name of my cookies are different from the requested ones

### ISSUE THREAD

**Issue by RedSquirrel87** [trevorhobenshield/amazon_photos#4]
In the setup section you request to export for UBID_ACDCA and AT_ACBCA variables, but in my cookies I got "ubid-acbit" and "at-acbit" names. What should I do then? I have to export the original variables with my cookies values or change them to the my names?
I mean, should I use:
```
export UBID_ACBIT="..."
export AT_ACBIT="..."
```
or what?

P.s.: I already tried in both way but it never works (I always get the "AttributeError: 'NoneType' object has no attribute 'json'" error).

**Comment by trevorhobenshield** [comment]
Issue should now be fixed. See the readme for more details.

E.g. 
```python
ap = AmazonPhotos(tld='it')
```
