### ISSUE TITLE
Cannot download images

### ISSUE THREAD

**Issue by MonliH** [trevorhobenshield/amazon_photos#5]
Thanks for providing this awesome library; it is very, very helpful to have an unofficial API wrapper in Python!

Currently, it seems that Amazon changed their downloads API, and the `download` method no longer works. After a bit of digging, I believe it is because the old download URL now returns a 404:

https://github.com/trevorhobenshield/amazon_photos/blob/3b9c54af0014a6f02a354cfe057f6ca497f830af/amazon_photos/api.py#L283

Is there a workaround? I'm not really familiar with Amazon photos' undocumented API.

**Comment by trevorhobenshield** [comment]
Thanks! I can't replicate this issue, downloads are still working currently.
