### ISSUE TITLE
Its probably my fault.

### ISSUE THREAD

**Issue by FinnAbrahamson** [trevorhobenshield/amazon_photos#7]
I might just be an idiot:
I'm pulling my cookies from mozilla's sqlight db. The amazon cookies I see there are named: 'session-id', 'ubid-main', and 'at-main'. I'm assigning values to my dictionary file as such; but I keep getting the following error:

  File C:\ProgramData\anaconda3\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\absol\untitled0.py:13
    ap = AmazonPhotos(

  File ~\AppData\Roaming\Python\Python311\site-packages\amazon_photos\_api.py:82 in __init__
    self.root = self.get_root()

  File ~\AppData\Roaming\Python\Python311\site-packages\amazon_photos\_api.py:907 in get_root
    root = r.json()['data'][0]

AttributeError: 'NoneType' object has no attribute 'json'

I'm assuming I am doing the whole cookie thing wrong, but might need someone to spell it out for me.
On another note: I provide a service to incarcerated individuals, where I curate photos and have them printed and mailed to them through the Amazon Photos platform, but I currently have to manually enter their orders in. I keep a database of the photos locally, and have the entire catalog uploaded to Amazon Photos. It would be AWESOME if there was a way to use this API to assemble photo orders and printing projects programmatically.

Sorry if this is all just a waste of your time, and thank you sooo much for the work you are doing!

**Comment by marketviable** [comment]
Not your fault - I had the same issues.... had to rename the cookies in the code to fix it. I added a pull request that should work for you (keep the "main" names in your cookie IDs)

#8

**Comment by FinnAbrahamson** [comment]
Thank you sooo much!

**Comment by trevorhobenshield** [comment]
Thanks for catching this @marketviable. I can't merge your PR because I'm dropping the env var option as it will potentially raise the same issue in the future. Users will now copy, at minimum, the essential session-id and ubid/at variants alongside any other special cookies that may be required in certain countries.
